# Generated by Django 5.0.6 on 2024-05-08 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_depositor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, verbose_name='Сумма')),
                ('annual_percentage', models.FloatField(default=0.0, verbose_name='Годовой процент')),
                ('dc', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата записи')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.depositor')),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
            },
        ),
    ]
