# Generated by Django 5.0.5 on 2024-05-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bankowner_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
    ]
