# Generated by Django 5.0.6 on 2024-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_depositor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositor',
            name='role',
            field=models.CharField(choices=[('depositorPremium', 'Вкладчик с высоким рейтингом'), ('depositorNormal', 'Вкладчик с обычным рейтингом'), ('depositorGarbage', 'Вкладчик из черного списка')], max_length=20, verbose_name='Роль'),
        ),
    ]
