# Generated by Django 5.0.5 on 2024-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, default='', max_length=10, verbose_name='День рождения'),
        ),
    ]
