# Generated by Django 5.0.6 on 2024-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_depositor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositor',
            name='birthday',
            field=models.DateField(blank=True, default='', max_length=10, verbose_name='День рождения'),
        ),
    ]
