# Generated by Django 5.0.5 on 2024-05-06 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='dc',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи'),
        ),
    ]
