# Generated by Django 5.0.5 on 2024-05-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_deposit_dc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='dc',
        ),
    ]
