# Generated by Django 5.0.6 on 2024-05-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_depositor_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositor',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='День рождения'),
        ),
    ]
