# Generated by Django 5.0.5 on 2024-05-06 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_deposit_dc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='dc',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата записи'),
        ),
    ]
