# Generated by Django 5.0.6 on 2024-05-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bankworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankworker',
            name='role',
            field=models.CharField(choices=[('director', 'Директор'), ('cashier', 'Кассир'), ('booker', 'Бухгалтер'), ('call_center_worker', 'Работник call-центра')], max_length=20, verbose_name='Роль'),
        ),
    ]
