# Generated by Django 5.0.6 on 2024-05-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bankworker_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankWorker',
        ),
    ]
