# Generated by Django 5.0.6 on 2024-05-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_bankworker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depositor',
        ),
    ]
