# Generated by Django 5.0.6 on 2024-05-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_depositor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Почта')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('director', 'Директор'), ('cashier', 'Кассир'), ('booker', 'Бухгалтер'), ('call_center_worker', 'Работник call-центра')], max_length=20, verbose_name='Роль')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bank')),
            ],
            options={
                'verbose_name': 'Работник банка',
                'verbose_name_plural': 'Работники банка',
            },
        ),
    ]
