# Generated by Django 5.0.6 on 2024-05-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bankworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depositor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Почта')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('depositorPremium', 'Вкладчик с высоким рейтингом'), ('depositorNormal', 'Вкладчик с обычным рейтингом'), ('depositorGarbage', 'Вкладчик из черного списка')], max_length=20, verbose_name='Роль')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bank')),
            ],
            options={
                'verbose_name': 'Вкладчик',
                'verbose_name_plural': 'Вкладчики',
            },
        ),
        migrations.DeleteModel(
            name='BankWorker',
        ),
    ]
