# Generated by Django 5.0.6 on 2024-05-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_depositor2_delete_bankworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositor2',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='depositor2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='depositor2',
            name='role',
        ),
        migrations.RemoveField(
            model_name='depositor2',
            name='telephone',
        ),
    ]
