# Generated by Django 5.0.6 on 2024-05-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_depositor2_bank_remove_depositor2_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depositor2',
        ),
    ]
