# Generated by Django 5.0.6 on 2024-05-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_deposit_dc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='depositor',
        ),
    ]
