# Generated by Django 5.0.6 on 2024-05-07 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_deposit_currency_remove_deposit_depositor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='dc',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=10, null=True, verbose_name='Дата записи'),
        ),
    ]
