# Generated by Django 5.0.6 on 2024-05-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_deposit_delete_bankworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='dc',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='depositor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='core.depositor'),
        ),
    ]
