# Generated by Django 5.0.6 on 2024-05-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_deposit_dc_alter_deposit_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='name',
            field=models.CharField(default='Депозит', max_length=100, verbose_name='Название'),
        ),
    ]
