# Generated by Django 5.0.6 on 2024-05-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_deposit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='depositor',
        ),
    ]
