# Generated by Django 5.0.6 on 2024-05-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_deposit_currency_remove_deposit_depositor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='name',
        ),
    ]
