# Generated by Django 5.0.6 on 2024-05-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_deposit_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
