# Generated by Django 5.0.6 on 2024-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositor',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
